# Generated by Django 3.1.2 on 2021-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210111_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('health', 'health'), ('fitness', 'fitness'), ('lifestyle', 'lifestyle'), ('workout', 'workout')], max_length=20),
        ),
    ]
