# Generated by Django 3.1.2 on 2021-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210111_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='highlight_text',
            field=models.TextField(default=True),
        ),
    ]
