# Generated by Django 3.1.2 on 2021-02-22 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210221_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(default='5 min', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='highlight_text',
            field=models.TextField(default='Keep Moving Forward'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
