# Generated by Django 3.1.2 on 2021-04-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
